### ISSUE TITLE
Hotfix 1.8.1

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/portal#299]
### Descrptiion

Provide a hotfix 1 of portal v1.8.0

### Why

https://github.com/eclipse-tractusx/portal-backend/issues/718
https://github.com/eclipse-tractusx/portal-backend/pull/719
https://github.com/eclipse-tractusx/portal/pull/298

### Tasks

- [x] bump version, update docs and changelog
- [x] release
- [x] Merge in release candidate branches
- [x] inform team members of the deployment status
