### ISSUE TITLE
Enhance LocalDev umbrella chart for more widespread usage

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/portal#399]
### Description

We want to be less reliant on some hosted environment for our development work.
Therefore the [LocalDev umbrella chart](https://github.com/eclipse-tractusx/portal/blob/main/charts/localdev/README.md) should be enhanced.
Especially, also the frontend devs should be able to setup the LocalDev in order to have a local backed available.

### Acceptance Criteria

- [x] Upgrade portal to R24.08 (currently still on R25.05)
- [x] Look into updating LocalDev with latest images built from main branches of frontend, backend, assets and registration-frontend (currently only the portal chart is updated with those, not LocalDev) -- maybe referencing the portal chart via file system?
- [x] all team members should update the [README.md](https://github.com/eclipse-tractusx/portal/blob/main/charts/localdev/README.md) if they gathered useful information when setting up LocalDev on their device (for instance - but not limited to - experience in combination with WSL, Proxy or alternative Container/virtual machine managers than Docker)

**Comment by evegufy** [comment]
All done from @ntruchsess's and my side. @oyo still wanted to update the documentation with his experience.

**Comment by MaximilianHauer** [comment]
@oyo  please provide your feedback until monday 
@evegufy  / @ntruchsess  please check with the colleagues if the topic is solved.

**Comment by oyo** [comment]
@evegufy @MaximilianHauer I have added the steps to setup cntlm on Mac or Linux https://github.com/eclipse-tractusx/portal/issues/399
